---
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt-certificates:/etc/letsencrypt
    networks:
      - npm_network
networks:
  npm_network:
    driver: bridge
volumes:
  data:
  letsencrypt-certificates: