version: '3'
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: always
    ports:
      - "80:80"       # HTTP
      - "81:81"       # Admin interface
      - "443:443"     # HTTPS
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - portainer_data:/data
      - portainer_letsencrypt:/etc/letsencrypt

volumes:
  portainer_data:
    driver: local
  portainer_letsencrypt:
    driver: local