version: '3.8'

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - jellyfin_config:/config
      - jellyfin_media:/media
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
      - 7359:7359/udp
    restart: unless-stopped
# Using persisitent volumes to support image updates via watchtower.
volumes:
  jellyfin_config:
  jellyfin_media: