---
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    ports:
      - "3000:3000/tcp" # first install
      - "53:53/tcp" # DNS Resolution
      - "53:53/udp" # DNS Resolution
      - "80:80/tcp" # WebUI
      - "443:443/tcp" # DNS-over-HTTPS
      - "853:853/tcp" # DNS-over-QUIC/DNS-over-TLS
    volumes:
      - data:/opt/adguardhome/work
      - config:/opt/adguardhome/conf
    restart: always

volumes:
  data:
  config: