---
services:
  uptime_kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - data:/app/data
    restart: always

volumes:
  data: